### ISSUE TITLE
[TZ] Kazakhstan/Almaty

### ISSUE THREAD

**Issue by ildar** [open-meteo/geocoding-api#15] opened 2024-05-05 13:44 UTC
Kazakhstan recently changed the timezones for most of the country.
Please change accordingly. Some apps relying on your TZ infos.

**Comment by patrick-zippenfenig** [comment] 2024-05-06 10:08
Thanks for the report. I will schedule the update for July.

**Comment by ildar** [comment] 2024-05-06 10:39
Excuse me, you mean July this year?
Is there a page on the workflow you're in that I can read?

**Comment by patrick-zippenfenig** [comment] 2024-05-06 10:43
There are instructions on the readme, but I expect larger work in the upstream databases is required to update it. I do not have time in the next weeks to start working on it

**Comment by papjul** [comment] 2024-05-06 11:03
As mentioned in breezy-weather/breezy-weather#1038 in a later message, updating the database would change nothing because GeoNames also uses Asia/Almaty.

Either GeoNames is not up-to-date or timezone name was preserved and your timezone database on your system is not up-to-date. I think the second option is more likely. On an Android system >= 10, you should get automatic updates according to docs: https://source.android.com/docs/core/permissions/timezone-rules?hl=en#timezone-apex

**Comment by ildar** [comment] 2024-05-06 11:06
Asia/Almaty is the subject of this issue, it is one of the Kazakhstan
cities that have TZ changed. So when Almaty time is changed, everyone (me
at least) will be happy

**Comment by papjul** [comment] 2024-05-06 11:23
Yes, timezones are based on boundaries, we don't update each city manually.

After looking at tzdata source code, I'm now convinced the issue is neither on GeoNames or Open-Meteo side.

As you can see in this commit: https://github.com/eggert/tz/commit/95a16c87f21c4643055482429dad921357a630c9

It is scheduled for Asia/Almaty to switch to UTC+5 starting from March 1st.

This update was released in tzdata v2024a, on 2024-02-01. An up-to-date device will have no issue. If it already is, please contact your manufacturer to let them know about the issue.

**Comment by patrick-zippenfenig** [comment] 2024-05-06 11:35
tzdata `2024a` is already installed on Open-Meteo API servers. If timezone handling is done on the client, the client also needs the correct timezone database.

The API return the correct timezone name and offset: https://api.open-meteo.com/v1/forecast?latitude=48&longitude=68&hourly=temperature_2m&timezone=auto

```json
{"latitude":48.0,"longitude":68.0,"utc_offset_seconds":18000,"timezone":"Asia/Almaty","timezone_abbreviation":"+05"}
```

**Comment by papjul** [comment] 2024-05-06 11:44
We don't use offset, we use the timezone name, because that's how it works with other weather sources we use, and it handles DST and other particularities just fine.

However, if the system on which the client is installed has an outdated timezone database, the time will also be displayed outdated.

**Comment by ildar** [comment] 2024-05-06 11:47
I see now.
I'm sorry this issue seems to be invalid. As Patrick shows, OM returns
right TZ infos (GMT+5) so no problem on OM's side.
Sorry for the noise.

**Closed** 2024-05-06 17:28 UTC
